NIFTY50_TICKERS = [
    "RELIANCE.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS", "TCS.NS", "LT.NS", "ITC.NS", "KOTAKBANK.NS",
    "SBIN.NS", "BHARTIARTL.NS", "HINDUNILVR.NS", "BAJFINANCE.NS", "ASIANPAINT.NS", "AXISBANK.NS", "HCLTECH.NS",
    "ULTRACEMCO.NS", "MARUTI.NS", "SUNPHARMA.NS", "TITAN.NS"
]

SP500_TICKERS = [
    "AAPL", "MSFT", "NVDA", "AMZN", "GOOGL", "META", "TSLA", "BRK-B", "UNH", "LLY", "JPM", "V", "AVGO", "XOM", "PG",
    "MA", "HD", "MRK", "PEP"
]
